### ISSUE TITLE
Add ability to render the displayed SVG to an image format (png preferably, but whatever)

### ISSUE THREAD

**Issue by ptmccarthy** [ptmccarthy/wikimapper#46]
Would be neat to export static images, and is a stepping stone toward #26

**Comment by tomzx** [comment]
One way you could achieve this is to use a service where you can send the svg and it will return you a png file.

My preferred solution however is an in-browser svg-to-png javascript such as https://github.com/exupero/saveSvgAsPng. I've used similar js to save d3 charts without too much issue.

**Comment by ptmccarthy** [comment]
Awesome! Thanks for the tip I will look into it.

In the upcoming 2.0 release I've got SVG exporting implemented via http://nytimes.github.io/svg-crowbar but it really only gets me half way to where I'd like to be. Exporting images would be preferable to a raw svg.
